# Generated by Django 4.1.3 on 2022-11-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentencas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sentenca',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sentenca',
            name='observacoes',
            field=models.CharField(help_text='Observações adicionais como página de livro, etc', max_length=256, null=True),
        ),
    ]
