# Generated by Django 4.1.3 on 2022-11-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentencas', '0003_alter_area_usuario_alter_autor_usuario_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('nome', 'usuario'), name='unique_nome_usuario_area'),
        ),
        migrations.AddConstraint(
            model_name='autor',
            constraint=models.UniqueConstraint(fields=('nome', 'usuario'), name='unique_nome_usuario_autor'),
        ),
    ]
