# Generated by Django 4.1.3 on 2022-11-13 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentencas', '0004_area_unique_nome_usuario_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
    ]
