# Generated by Django 4.1.3 on 2022-11-14 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracoes_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatorios_por_dia', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, help_text='Quantidade de relatórios a receber por dia', max_length=1)),
                ('tipo_de_relatorio', models.CharField(choices=[('C', 'Completo'), ('S', 'Simples')], default='S', help_text='Simples, contém apenas uma sentença; Completo, possui uma sentença por área', max_length=1)),
                ('usuario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
