# Generated by Django 4.1.3 on 2022-11-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracoes_usuario',
            name='tipo_de_relatorio',
            field=models.CharField(choices=[('SIMPLES', 'Simples'), ('COMPLETO', 'Completo')], default='SIMPLES', help_text='Simples, contém apenas uma sentença; Completo, possui uma sentença por área', max_length=8),
        ),
    ]
