# Generated by Django 4.1.3 on 2022-11-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_configuracoes_usuario_relatorios_por_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracoes_usuario',
            name='tipo_de_relatorio',
            field=models.CharField(choices=[('S', 'Simples: Uma sentença geral'), ('C', 'Completo: Uma sentença por área')], default='S', help_text='Simples, contém apenas uma sentença; Completo, possui uma sentença por área', max_length=32),
        ),
    ]
