# Generated by Django 4.1.3 on 2022-11-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_recuperadordesenha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recuperadordesenha',
            name='token',
            field=models.CharField(help_text='Token de recuperação de senha', max_length=128),
        ),
    ]
