# Generated by Django 4.1.3 on 2022-11-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_recuperadordesenha_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracoes_usuario',
            name='relatorios_por_dia',
            field=models.CharField(choices=[('0', 'Não enviar e-mail'), ('1', 'Manhã somente'), ('2', 'Manhã e Tarde'), ('3', 'Manhã, Tarde e Noite')], default=1, help_text='Quantidade de relatórios a receber por dia', max_length=32),
        ),
    ]
